### ISSUE TITLE
[Feat] 사용자 정보 기반 추천 도서 기능 개발

### ISSUE THREAD

**Issue by jiooong** [BookWise2024/Back-end#13]
## **Description**

- 메인페이지 내 사용자 정보 기반 추천 도서 개발

## **Todo**

- [x]  큰 카테고리 30개 기반 상세 도서 검색 시 선호 카테고리 클릭 수 추가되는 기능 구현
- [ ]  추천 정보 GET
- [ ]  추천을 위한 사용자 정보 POST
