### ISSUE TITLE
[Feat] 위시카테고리 조회 기능 및 도서 상세정보 기능 추가

### ISSUE THREAD

**Issue by doonghui** [BookWise2024/Back-end#16]
## **Description**

- 위시리스트 카테고리 조회 기능 및 스웨거 추가

## **Todo**

- [x]  위시리스트카테고리 엔티티
- [x]  위시리스트카테고리 조회 service 
- [x]  위시리스트카테고리 조회 controller
- [x]  도서 상세정보 조회 추가
