### ISSUE TITLE
[Feat] 도서관initDB 수정 및 카카오 로그인 시큐리티 적용 

### ISSUE THREAD

**Issue by doonghui** [BookWise2024/Back-end#20]
## **Description**

- 도서관 initDB 수정
- 시큐리티를 카카오 로그인에 적용하기

## **Todo**
- [x]  도서관 initDB 수정
- [ ]  카카오 로그인 시큐리티 적용
- [ ] 스웨거 헤더에 Authorization 적용
